# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "model.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bmodel.proto\x12\x0f\x66l_common.proto"1\n\x0fModelParameters\x12\r\n\x05round\x18\x01 \x01(\r\x12\x0f\n\x07weights\x18\x02 \x01(\x0c"n\n\x0c\x43lientUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\r\x12\x15\n\rdelta_weights\x18\x03 \x01(\x0c\x12\x12\n\nlocal_loss\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\t"b\n\x10\x41ggregatedUpdate\x12\r\n\x05round\x18\x01 \x01(\r\x12\x18\n\x10\x61ggregated_delta\x18\x02 \x01(\x0c\x12\x13\n\x0bnum_clients\x18\x03 \x01(\r\x12\x10\n\x08\x64p_sigma\x18\x04 \x01(\x01"\x07\n\x05\x45mpty"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xfb\x01\n\x10\x46\x65\x64\x65ratedService\x12K\n\x0f\x44istributeModel\x12 .fl_common.proto.ModelParameters\x1a\x16.fl_common.proto.Empty\x12G\n\x10SendClientUpdate\x12\x1d.fl_common.proto.ClientUpdate\x1a\x14.fl_common.proto.Ack\x12Q\n\x14SendAggregatedUpdate\x12!.fl_common.proto.AggregatedUpdate\x1a\x16.fl_common.proto.EmptyBH\n\x1b\x63om.example.fl_common.protoZ)github.com/your_org/fl-common/proto;protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "model_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\033com.example.fl_common.protoZ)github.com/your_org/fl-common/proto;proto"
    )
    _globals["_MODELPARAMETERS"]._serialized_start = 32
    _globals["_MODELPARAMETERS"]._serialized_end = 81
    _globals["_CLIENTUPDATE"]._serialized_start = 83
    _globals["_CLIENTUPDATE"]._serialized_end = 193
    _globals["_AGGREGATEDUPDATE"]._serialized_start = 195
    _globals["_AGGREGATEDUPDATE"]._serialized_end = 293
    _globals["_EMPTY"]._serialized_start = 295
    _globals["_EMPTY"]._serialized_end = 302
    _globals["_ACK"]._serialized_start = 304
    _globals["_ACK"]._serialized_end = 343
    _globals["_FEDERATEDSERVICE"]._serialized_start = 346
    _globals["_FEDERATEDSERVICE"]._serialized_end = 597
# @@protoc_insertion_point(module_scope)
